{
  "info": {
    "author": "Thomas Deniffel",
    "author_email": "tdeniffel@gmail.com",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 4 - Beta",
      "Intended Audience :: Developers",
      "Programming Language :: Python",
      "Programming Language :: Python :: 3 :: Only",
      "Programming Language :: Python :: 3.6",
      "Programming Language :: Python :: 3.7"
    ],
    "description": "Presentable Exceptions\n======================\n\nThis is a module for django restframework, in which modules can specifiy exceptions in an\nextra file with an key an description. At some place in the code, they can be fetched by \nthe package and key and bubble up to the view. Here a mixin detects them and creates a \nproper response for an fat-client, which can show them then to to user - thus the exceptions\nare presentable.\n\nGetting started\n---------------\n\nSay, you have a module, like `auth_api` which is registered in `INSTALLED_APPS` in the Django\n`settings.py`. Create a new file `auth_api/presentable_exceptions.py` with this content\n\n```python\npresentable_exceptions = {\n    'client': [\n        ('not-enough-data-to-delete-user', 'You did not provide enough data, that we can delete the user {username}')\n    ],\n    'server': [\n        ('backend-connection-lost', 'We lost the connection to the backend'),\n    ]\n}\n```\n\nThis file can be in every module and consists of two parts: The exceptions, that are the clients \nfault and the exceptions that are our fault. The first will cause a 4xx error, the latter a 5xx.\n\nSay, you have now an View somewhere, like that:\n\n```python\nclass MeView(WithPresentableException, APIView):\n\n    def get(self, request):\n        data = some_function_with_a_deep_call_stack()\n        return Response(data)\n```\n\nThis will call multiple function and somewhere there is the function `boom()` called:\n\n```python\ndef boom():\n    raise PresentableException.of('auth_api', 'backend-connection-lost')\n\n\ndef some_function_with_a_deep_call_stack():\n    # ...\n    boom()\n    # ...\n```\n\nThis `PresentableException` will be an `PresentableServerException` and bubble up into \nthe Mixing `WithPresentableException` specified in the view above, which generates \na proper response (with a 5xx code in this case).\n\n\n\n\n\n",
    "description_content_type": "text/markdown",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "https://github.com/tom-010/django-presentable-exception",
    "keywords": "",
    "license": "Apache2",
    "maintainer": "",
    "maintainer_email": "",
    "name": "django-presentable-exception",
    "package_url": "https://pypi.org/project/django-presentable-exception/",
    "platform": "",
    "project_url": "https://pypi.org/project/django-presentable-exception/",
    "project_urls": {
      "Homepage": "https://github.com/tom-010/django-presentable-exception"
    },
    "release_url": "https://pypi.org/project/django-presentable-exception/0.0.1/",
    "requires_dist": [
      "Django (>=3.2.0)",
      "djangorestframework (>=3.12.0)",
      "find-class (>=0.0.1exception-safe>=0.0.3)"
    ],
    "requires_python": ">=3",
    "summary": "Presentable Exceptions for Django Restframework Projects",
    "version": "0.0.1",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 12124913,
  "releases": {
    "0.0.1": [
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "eab251ba05f4ebe955102b6378d430a483f6cb5fa885a21a9b9852ce5c5c5e46",
          "md5": "6576612579ae1eafebf3cc6f863fa167",
          "sha256": "b5d0ff2ccfec39d88c8bef6a46b402b59e41ce1fc47e997fd277ae98eed0b4ff"
        },
        "downloads": -1,
        "filename": "django_presentable_exception-0.0.1-py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "6576612579ae1eafebf3cc6f863fa167",
        "packagetype": "bdist_wheel",
        "python_version": "py3",
        "requires_python": ">=3",
        "size": 9360,
        "upload_time": "2021-11-25T17:03:15",
        "upload_time_iso_8601": "2021-11-25T17:03:15.034432Z",
        "url": "https://files.pythonhosted.org/packages/ea/b2/51ba05f4ebe955102b6378d430a483f6cb5fa885a21a9b9852ce5c5c5e46/django_presentable_exception-0.0.1-py3-none-any.whl",
        "yanked": false,
        "yanked_reason": null
      },
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "15e255045e69d574a906a9307a71aa958bac9c67a1e3d0da379e86819c1d0aca",
          "md5": "1dd9198cc621c41032ebd95faef9233c",
          "sha256": "c02bfc33221698de5b9186baafad6a2dd7aa6b834c866b67b91e581f71797a31"
        },
        "downloads": -1,
        "filename": "django-presentable-exception-0.0.1.tar.gz",
        "has_sig": false,
        "md5_digest": "1dd9198cc621c41032ebd95faef9233c",
        "packagetype": "sdist",
        "python_version": "source",
        "requires_python": ">=3",
        "size": 10410,
        "upload_time": "2021-11-25T17:03:16",
        "upload_time_iso_8601": "2021-11-25T17:03:16.831109Z",
        "url": "https://files.pythonhosted.org/packages/15/e2/55045e69d574a906a9307a71aa958bac9c67a1e3d0da379e86819c1d0aca/django-presentable-exception-0.0.1.tar.gz",
        "yanked": false,
        "yanked_reason": null
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "eab251ba05f4ebe955102b6378d430a483f6cb5fa885a21a9b9852ce5c5c5e46",
        "md5": "6576612579ae1eafebf3cc6f863fa167",
        "sha256": "b5d0ff2ccfec39d88c8bef6a46b402b59e41ce1fc47e997fd277ae98eed0b4ff"
      },
      "downloads": -1,
      "filename": "django_presentable_exception-0.0.1-py3-none-any.whl",
      "has_sig": false,
      "md5_digest": "6576612579ae1eafebf3cc6f863fa167",
      "packagetype": "bdist_wheel",
      "python_version": "py3",
      "requires_python": ">=3",
      "size": 9360,
      "upload_time": "2021-11-25T17:03:15",
      "upload_time_iso_8601": "2021-11-25T17:03:15.034432Z",
      "url": "https://files.pythonhosted.org/packages/ea/b2/51ba05f4ebe955102b6378d430a483f6cb5fa885a21a9b9852ce5c5c5e46/django_presentable_exception-0.0.1-py3-none-any.whl",
      "yanked": false,
      "yanked_reason": null
    },
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "15e255045e69d574a906a9307a71aa958bac9c67a1e3d0da379e86819c1d0aca",
        "md5": "1dd9198cc621c41032ebd95faef9233c",
        "sha256": "c02bfc33221698de5b9186baafad6a2dd7aa6b834c866b67b91e581f71797a31"
      },
      "downloads": -1,
      "filename": "django-presentable-exception-0.0.1.tar.gz",
      "has_sig": false,
      "md5_digest": "1dd9198cc621c41032ebd95faef9233c",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": ">=3",
      "size": 10410,
      "upload_time": "2021-11-25T17:03:16",
      "upload_time_iso_8601": "2021-11-25T17:03:16.831109Z",
      "url": "https://files.pythonhosted.org/packages/15/e2/55045e69d574a906a9307a71aa958bac9c67a1e3d0da379e86819c1d0aca/django-presentable-exception-0.0.1.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}