{
  "info": {
    "author": "Jo√£o Vitor Ceolin Prudente",
    "author_email": "",
    "bugtrack_url": null,
    "classifiers": [],
    "description": "# Py Monadic Error Handling Documentation\r\n\r\n## Instalation\r\n<p>The library is available via pip through the following command:</p>\r\n\r\n```\r\npip install py-monadic-error-handling\r\n```\r\n\r\n## How to use\r\n<p>First import the safe decorator from py_monadic_error_handling.</p>\r\n\r\n```\r\nfrom py_monadic_error_handling import safe\r\n```\r\n\r\n<p>Then decorate your functions with the safe decorator.</p>\r\n\r\n```\r\n@safe\r\ndef func1(n1, n2): \r\n    return n1 + n2\r\n\r\n@safe\r\ndef func2(n1, n2): \r\n    return n1 / n2\r\n```\r\n\r\n<p>Each of those functions will return a Ok or Err object, witch are subclasses of Result and may take Ok or Err objects as parameters.</p>\r\n<p>If they return a Ok object, the function executed with no errors and the value can be accessed via the unwrap method.</p>\r\n\r\n```\r\nres = func1(1, 0).unwrap()\r\nprint(res)\r\n>>> 1\r\n```\r\n\r\n<p>If they return a Err object, the function executed with an error and the error can be raised via the unwrap method.</p>\r\n<p>unwrap takes no arguments and raise an exception or returns any</p>\r\n\r\n```\r\nres = func2(1, 0).unwrap()\r\n>>> ZeroDivisionError: division by zero\r\n```\r\n\r\n<p>You can access the value of the Ok object directly by using the Ok property or the error type in an Err object directly by using the Err property.</p>\r\n\r\n```\r\nres = func1(1, 0).Ok\r\nprint(res)\r\n>>> 1\r\nres = func2(1, 0).Err\r\nprint(res)\r\n>>> division by zero\r\n```\r\n\r\n<p>You can know if the function returned a Ok or Err object by using the is_ok and is_err methods.</p>\r\n<p>Both methods take no arguments and return a bool</p>\r\n\r\n```\r\nres = func1(1, 0).is_ok()\r\n>>> True\r\nres = func2(1, 0).is_err()\r\n>>> True\r\n```\r\n\r\n<p>You can safely unwrap an Ok or Err object with the unwrap_or method.</p>\r\n<p>unwrap_or takes one argument of any type.</p>\r\n<p>If the object is an instance of Ok, it returns object.Ok.</p>\r\n<p>If the object is an instance of Err, it returns the argument you entered.</p>\r\n\r\n```\r\nres = func1(1, 0).unwrap_or(-1)\r\nprint(res)\r\n>>> 1\r\nres = func2(1, 0).unwrap_or(-1)\r\nprint(res)\r\n>>> -1\r\n```\r\n\r\n<p>You can safely unwrap an Ok or Err object with the unwrap_or_else method.</p>\r\n<p>unwrap_or_else takes a function as its argument.</p>\r\n<p>The function takes an exception as its argument and may or may not return a value.</p>\r\n<p>If the object is an instance of Ok, it returns object.Ok.</p>\r\n<p>If the object is an instance of Err, it executes the function with the object.Err as its parameter and return its return value.</p>\r\n\r\n```\r\ndef handle_error(e):\r\n    print(e)\r\n    return -1\r\n\r\nres = func1(1, 0).unwrap_or_else(handle_error)\r\nprint(res)\r\n>>> 1\r\nres = func2(1, 0).unwrap_or_else(handle_error)\r\n>>> division by zero\r\nprint(res)\r\n>>> -1\r\n```\r\n\r\n## Railway Error Handling\r\n<p>By chaining functions decorated with safe, each function will excecute and if there is an error, it will return an Err object that will be caried through every function that depends on its return without executing them, othewise it will return an Ok value that can be taken as normal as argument for any other function decorated with safe</p>\r\n    \r\n```\r\nn1 = func1(1, 0)\r\n>>> Ok(1)\r\nn2 = func1(2, -2)\r\n>>> Ok(0)\r\nn3 = func2(n1, n2)\r\n>>> Err(ZeroDivisionError)\r\nn4 = func1(n3, 3)\r\n>>> Err(ZeroDivisionError)\r\nn5 = func1(n2, n1)\r\n>>> Ok(0)\r\n```\r\n\r\n<p>In this exemple, func1(n3, 3) is never executed because it depends on the return of a function that executed with an error, but func1(n1, 4) executes, because even though it executes later on the chain, it depends only on the return of functions that executed without any errors</p>\r\n",
    "description_content_type": "text/markdown",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "",
    "keywords": "",
    "license": "",
    "maintainer": "",
    "maintainer_email": "",
    "name": "py-monadic-error-handling",
    "package_url": "https://pypi.org/project/py-monadic-error-handling/",
    "platform": null,
    "project_url": "https://pypi.org/project/py-monadic-error-handling/",
    "project_urls": null,
    "release_url": "https://pypi.org/project/py-monadic-error-handling/1.1.1/",
    "requires_dist": null,
    "requires_python": "",
    "summary": "Monadic error handling implementation for python functions.",
    "version": "1.1.1",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 15299516,
  "releases": {
    "1.1.1": [
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "e5455a14e0e5cf00e01fed11175a0a68b84e042ab72e66a259845bb1385db4ac",
          "md5": "3e7e6a91eb7b72200284670fa1954395",
          "sha256": "47b0359bd586468c270049fb14218a560bb68e0a3c1ca12fd2fb8a3a5c4ec371"
        },
        "downloads": -1,
        "filename": "py_monadic_error_handling-1.1.1.tar.gz",
        "has_sig": false,
        "md5_digest": "3e7e6a91eb7b72200284670fa1954395",
        "packagetype": "sdist",
        "python_version": "source",
        "requires_python": null,
        "size": 2762,
        "upload_time": "2022-10-04T07:51:49",
        "upload_time_iso_8601": "2022-10-04T07:51:49.468434Z",
        "url": "https://files.pythonhosted.org/packages/e5/45/5a14e0e5cf00e01fed11175a0a68b84e042ab72e66a259845bb1385db4ac/py_monadic_error_handling-1.1.1.tar.gz",
        "yanked": false,
        "yanked_reason": null
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "e5455a14e0e5cf00e01fed11175a0a68b84e042ab72e66a259845bb1385db4ac",
        "md5": "3e7e6a91eb7b72200284670fa1954395",
        "sha256": "47b0359bd586468c270049fb14218a560bb68e0a3c1ca12fd2fb8a3a5c4ec371"
      },
      "downloads": -1,
      "filename": "py_monadic_error_handling-1.1.1.tar.gz",
      "has_sig": false,
      "md5_digest": "3e7e6a91eb7b72200284670fa1954395",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": null,
      "size": 2762,
      "upload_time": "2022-10-04T07:51:49",
      "upload_time_iso_8601": "2022-10-04T07:51:49.468434Z",
      "url": "https://files.pythonhosted.org/packages/e5/45/5a14e0e5cf00e01fed11175a0a68b84e042ab72e66a259845bb1385db4ac/py_monadic_error_handling-1.1.1.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}